working_dir: tmp
num_epochs: 30
data_params:
  data_dir: '/is/rg/al/Data/alpha_skat/new_ramsch_level_0'
  batch_size: 128
model_params:
  learning_rate: 0.001
  arch_params:
    name: resnet9
    #name: TransformerModel
    #input_dim: 32
    #seq_len: 36
    #num_heads: 2
    #dim_feedforward: 2048
    #num_layers: 1
    #dropout: 0.0
    #resnet_params:
    #  layers: [1, 1, 1, 1]
    #  groups: 1
    #  width_per_group: 64