working_dir: tmp
num_epochs: 30
mode: value
data_params:
  data_dir: /is/rg/al/Data/alpha_skat/policy_and_value_big
  batch_size: 128
model_params:
  game: ramsch
  loss_function: "SmoothL1"
  optimizer_params:
    name: AdamW
    lr: 0.002
    weight_decay: 0.000001
  scheduler_params:
    gamma: 0.1
    step_size: "{int(0.8 * num_epochs)}"
  arch_params:
    name: resnet50