game_name: simple_ramsch
working_dir: "tmp"
num_games: 2
save_games: false
player_params:
  player_one:
    name: MCTSPlayer
    num_mcts_rollouts: 2000
    guessed_hands: 10
    exploration_weight: 2.0
    value_function_checkpoint: tmp/lightning_logs/version_120/checkpoints/epoch=11.ckpt
  player_two:
    name: MCTSPlayer
    num_mcts_rollouts: 2000
    guessed_hands: 10
    exploration_weight: 2.0
    value_function_checkpoint: tmp/lightning_logs/version_120/checkpoints/epoch=11.ckpt
  player_three:
    name: MCTSPlayer
    num_mcts_rollouts: 4000
    guessed_hands: 10
    exploration_weight: 2.0
