game_name: simple_ramsch
working_dir: "tmp"
num_games: 500
save_games: false
player_params:
  player_one:
    name: HardcodedPlayer
  player_two:
    #name: #RandomPlayer   #HardcodedPlayer
    name: NNPlayer
    checkpoint_path: tmp/lightning_logs/version_67/checkpoints/epoch=5.ckpt
  player_three:
    name: HardcodedPlayer
    #name: FullStateMCTSPlayer
    #num_mcts_rollouts: 10
    #exploration_weight: 2.0
    #softmax_temperature: 0.1
