game_name: simple_ramsch
working_dir: "tmp"
num_games: 200
save_games: false
player_params:
  player_one:
    name: FullStateMCTSPlayer
    num_mcts_rollouts: 100
    exploration_weight: 10.0
  player_two:
    name: FullStateMCTSPlayer
    num_mcts_rollouts: 100
    exploration_weight: 10.0
  player_three:
    name: FullStateMCTSPlayer
    num_mcts_rollouts: 100
    exploration_weight: 1.0
