game_name: simple_ramsch
working_dir: "tmp"
num_games: 3
save_games: true
player_params:
  player_one:
    name: FullStateMCTSPlayer
    num_mcts_rollouts: 1600
    exploration_weight: 2.0
    softmax_temperature: 0.1
  player_two:
    name: FullStateMCTSPlayer
    num_mcts_rollouts: 1600
    exploration_weight: 2.0
    softmax_temperature: 0.1
  player_three:
    name: FullStateMCTSPlayer
    num_mcts_rollouts: 1600
    exploration_weight: 2.0
    softmax_temperature: 0.1
