game_name: simple_ramsch
working_dir: "tmp"
num_games: 3
save_games: false
play_all_hand_rotations: false
player_params:
  player_one:
    name: MCTSPlayer
    __import__: configs/tournaments/mcts_random.yaml
  player_two:
    name: MCTSPlayer
    __import__: configs/tournaments/mcts_random.yaml
  player_three:
    name: MCTSPlayer
    __import__: configs/tournaments/mcts_random.yaml
