game_name: simple_ramsch
working_dir: "tmp"
num_games: 2
save_games: false
player_params:
  player_one:
    #name: HardcodedRamschPlayer
    name: MCTSPlayer
    num_mcts_rollouts: 4000
    guessed_hands: 10
    exploration_weight: 2.0
  player_two:
    name: MCTSPlayer
    num_mcts_rollouts: 4000
    guessed_hands: 10
    exploration_weight: 2.0
    #name: RandomPlayer   #HardcodedPlayer
    #name: NNPlayer
    #checkpoint_path: tmp/lightning_logs/version_67/checkpoints/epoch=5.ckpt
  player_three:
    #name: HardcodedPlayer
    name: MCTSPlayer
    num_mcts_rollouts: 4000
    guessed_hands: 10
    exploration_weight: 2.0
