game_name: simple_ramsch
working_dir: "tmp"
num_games: 3
save_games: false
play_all_hand_rotations: false
player_params:
  player_one:
    #name: HardcodedRamschPlayer
    name: MCTSPlayer
    num_mcts_rollouts: 16000
    guessed_hands: 10
    exploration_weight: 60.0
    policy_function_checkpoint: "" #/is/rg/al/Data/alpha_skat/best_checkpoints/ramsch_policy.ckpt
    value_function_checkpoint: ""
    softmax_temperature_for_saving: 0.1
    use_policy_for_init_hands: false
    use_policy_for_ucb: false
    epsilon: 0.0001
    init_hands_to_sample: 400
    policy_ucb_coef: 0.0
  player_two:
    name: MCTSPlayer
    num_mcts_rollouts: 16000
    guessed_hands: 10
    exploration_weight: 60.0
    policy_function_checkpoint: "" #/is/rg/al/Data/alpha_skat/best_checkpoints/ramsch_policy.ckpt
    value_function_checkpoint: ""
    softmax_temperature_for_saving: 0.1
    use_policy_for_init_hands: false
    use_policy_for_ucb: false
    epsilon: 0.0001
    init_hands_to_sample: 400
    policy_ucb_coef: 0.0
  player_three:
    name: MCTSPlayer
    num_mcts_rollouts: 16000
    guessed_hands: 10
    exploration_weight: 60.0
    policy_function_checkpoint: "" #/is/rg/al/Data/alpha_skat/best_checkpoints/ramsch_policy.ckpt
    value_function_checkpoint: ""
    softmax_temperature_for_saving: 0.1
    use_policy_for_init_hands: false
    use_policy_for_ucb: false
    epsilon: 0.0001
    init_hands_to_sample: 400
    policy_ucb_coef: 0.0
