game_name: simple_ramsch
working_dir: "tmp"
num_games: 20
save_games: true
play_all_hand_rotations: true
player_params:
  player_one:
    name: NNPlayer
    checkpoint_path: /is/rg/al/Data/alpha_skat/best_checkpoints/ramsch_resnet_50.ckpt
  player_two:
    name: NNPlayer
    checkpoint_path: /is/rg/al/Data/alpha_skat/best_checkpoints/ramsch_resnet_50.ckpt
    #name: MCTSPlayer
    #num_mcts_rollouts: 2000
    #guessed_hands: 5
    #exploration_weight: 60.0
    #value_function_checkpoint: ""
    #policy_function_checkpoint: ""
    #softmax_temperature_for_saving: 0.1
    #use_policy_for_init_hands: false
    #use_policy_for_ucb: false
  player_three:
    name: MCTSPlayer
    num_mcts_rollouts: 4000
    guessed_hands: 5
    exploration_weight: 60.0
    value_function_checkpoint: ""
    policy_function_checkpoint: tmp/lightning_logs/version_11/checkpoints/epoch=49.ckpt
    softmax_temperature_for_saving: 0.1
    use_policy_for_init_hands: true
    use_policy_for_ucb: false
    epsilon: 0.0001
    init_hands_to_sample: 200
