game_name: simple_ramsch
working_dir: "tmp"
num_games: 99
save_games: true
play_all_hand_rotations: true
player_params:
  player_one:
    name: NNPlayer
    checkpoint_path: /is/rg/al/Data/alpha_skat/best_checkpoints/ramsch_policy.ckpt
  player_two:
    name: NNPlayer
    checkpoint_path: /is/rg/al/Data/alpha_skat/best_checkpoints/ramsch_policy.ckpt
  player_three:    
    name: MCTSPlayer
    __import__:
      - configs/tournaments/mcts_nn.yaml
      - configs/checkpoints/ramsch/level1.yaml

