game_name: simple_ramsch
working_dir: "tmp"
num_games: 600
save_games: true
play_all_hand_rotations: true
player_params:
  player_one:
    name: NNPlayer
    #checkpoint_path: /is/rg/al/Data/alpha_skat/best_checkpoints/ramsch_value_and_policy.ckpt
    checkpoint_path: tmp/lightning_logs/version_11/checkpoints/epoch=49.ckpt
  player_two:
    name: NNPlayer
    checkpoint_path: /is/rg/al/Data/alpha_skat/best_checkpoints/ramsch_value_and_policy.ckpt
  player_three:
    name: MCTSPlayer
    num_mcts_rollouts: 1000
    guessed_hands: 10
    exploration_weight: 60.0
    #value_function_checkpoint: /is/rg/al/Data/alpha_skat/best_checkpoints/ramsch_value_and_policy.ckpt
    value_function_checkpoint: tmp/lightning_logs/version_11/checkpoints/epoch=49.ckpt
    policy_function_checkpoint: "" #/is/rg/al/Data/alpha_skat/best_checkpoints/ramsch_policy.ckpt
    softmax_temperature_for_saving: 0.1
